# GitHub action to make sure that the terraform docs in the README are
# up-to-date on every push to the main branch

name: Terraform docs

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Terraform docs in README
        uses: terraform-docs/gh-actions@v0.10.0
        with:
          config-file: '.terraform-docs.yml'
          output-file: README.md
          git-push: 'true'
          git-commit-message: 'docs: Update Terraform docs'
